import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth-utils";
import { generateCarePlanWithAI } from "@/lib/openai";

export async function POST(request: NextRequest) {
  try {
    const { user, error, status } = await getCurrentUser();
    if (error || !user) return NextResponse.json({ error }, { status });

    const body = await request.json();
    const { careRecipientId } = body;

    const careRecipient = await prisma.careRecipient.findFirst({
      where: { id: careRecipientId, primaryCaregiverId: user.id },
    });

    if (!careRecipient) {
      return NextResponse.json({ error: "Care recipient not found" }, { status: 404 });
    }

    // Generate care plan using AI
    let aiPlan;
    try {
      aiPlan = await generateCarePlanWithAI({
        firstName: careRecipient.firstName,
        lastName: careRecipient.lastName,
        age: careRecipient.age,
        conditions: careRecipient.conditions,
        allergies: careRecipient.allergies,
        medications: careRecipient.currentMedications,
        notes: careRecipient.notes,
      });
    } catch (aiError) {
      console.error("AI generation failed:", aiError);
      return NextResponse.json(
        { error: "Failed to generate care plan. Please check your OpenAI API key." },
        { status: 500 }
      );
    }

    // Deactivate old care plans
    await prisma.carePlan.updateMany({
      where: { careRecipientId, isActive: true },
      data: { isActive: false },
    });

    // Save the new care plan
    const carePlan = await prisma.carePlan.create({
      data: {
        title: `Care Plan for ${careRecipient.firstName} ${careRecipient.lastName}`,
        summary: aiPlan.summary || "Personalized care plan generated by AI",
        goals: aiPlan.goals || [],
        dailyRoutine: aiPlan.dailyRoutine || null,
        recommendations: aiPlan.recommendations || [],
        emergencyInfo: aiPlan.emergencyInfo || null,
        isAIGenerated: true,
        isActive: true,
        careRecipientId,
        createdById: user.id,
      },
    });

    return NextResponse.json({
      ...carePlan,
      goals: carePlan.goals as unknown as Array<Record<string, unknown>>,
      dailyRoutine: carePlan.dailyRoutine as unknown as Record<string, unknown>,
      recommendations: carePlan.recommendations as unknown as Array<Record<string, unknown>>,
      emergencyInfo: carePlan.emergencyInfo as unknown as Record<string, unknown>,
    });
  } catch (error) {
    console.error("Care plan API error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
